config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: 'd'

  authenticate :user do
    resources :events
    resources :children
    resources :event_days
    resources :schools
    resources :users
    namespace :event_days do
      resources :registrations
    end
  end

  get "/event_splashes/current_event", to: "event_splashes#current_event" 

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  authenticated :user do
    root to: "events#index", as: :authenticated_root
  end
  root to: redirect("/d/sign_in")
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :school
  has_many :children, dependent: :destroy
  accepts_nested_attributes_for :children

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum role: [:caregiver, :school_manager, :admin, :area_manager]

  def set_default_role
    self.role ||= :caregiver
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  
  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # after_save :register_all_events

  def index
    @users = User.all
  end
  
  def show
    @user = User.find(params[:id])
    render "show_#{current_user.role}"
  end
  
  def new
    @user = User.new
  end
  
  def create
    unless current_user.role == "admin"
      params[:role] = "caregiver"
    end

    @user = User.new(user_params)

    if @user.save
      flash[:notice] = "Welcome #{@user.name}, you've signed up"
      redirect_to user_path(@user)
    else
      flash.now[:alert] = "Could not create user"
      render :new, status: :unprocessable_entity
    end
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      flash[:notice] = "#{@user.name} updated successfully"
      redirect_to user_path(@user)
    else
      flash.now[:alert] = "Could not update user"
      render :edit, status: :unprocessable_entity
    end
  end
  
  def destroy
    @user = User.find(params[:id])
    
    if @user.destroy
      flash[:notice] = "Successfully removed user"
      redirect_to root_path
    else
      flash.now[:alert] = "Could not delete user"
    end
  end

  private

  def user_params
    params.require(:user).permit(:id, :role, :name, :phone, :email, :password, :password_confirmation, :school_id, children_attributes: [:id, :user_id, :name, :birthday, :level, :category, :allergies])
  end

  # def register_all_events
  #   self.school.events.each do |event|
  #     event.event_days.each do |ed|
  #       ed.registrations.create(event_day_id: ed.id, child_id: @child.id, attend_morning: false, attend_afternoon: false)
  #     end
  #   end
  # end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_child_fields.html.erb
<div class="child_fields_wrapper" data-new-record="<%= f.object.new_record? %>">
    <%= f.hidden_field :user_id %>

    <div class="child_field">
        <%= f.label :name %>
        <%= f.text_field :name %>
    </div>

    <div class="child_field">
        <%= f.label :birthday %>
        <%= f.date_field :birthday %>
    </div>

    <div class="child_field">
        <%= f.label :level %>
        <%= f.select :level, ["Kindy", "Land 1", "Land 2", "Sky 1", "Sky 2", "Galaxy 1", "Galaxy 2"] %>
    </div>

    <div class="child_field">
        <%= f.label :category %>
        <%= f.select :category, [["Gaibu", "gaibu"], ["Naibu", "naibu"], ["Yoyaku", "yoyaku"]] %>
    </div>

    <div class="child_field">
        <%= f.label :allergies %>
        <%= f.text_area :allergies %>
    </div>

    <%= button_tag "Remove Child", data: {action: "fields#remove"} %>
</div>

app/views/users/_form.html.erb
<%= form_with model: @user, data: {controller: :fields} do |form| %>

    <% if current_user.role == "admin" %>
        <%= form.label :role %>
        <%= form.select :role, [["Admin", "admin"], ["School Manager", "school_manager"], ["Parent", "caregiver"]] %>
    <% else %>
        <%= form.hidden_field :role, value: "caregiver" %>
    <% end %>

     <div class="user_fields">
        <%= form.label :school_id %>
        <%= form.collection_select :school_id, School.order(:name), :id, :name %>
    </div>

    <div class="user_fields">
        <%= form.label :name %>
        <%= form.text_field :name %>
    </div>

    <div class="user_fields">
        <%= form.label :phone %>
        <%= form.text_field :phone %>
    </div>

    <div class="user_fields">
        <%= form.label :email %>
        <%= form.text_field :email %>
    </div>

    <div class="user_fields">
        <%= form.label :password, "Temp password" %>
        <%= form.text_field :password %>
    </div>

    <div class="user_fields">
        <%= form.label :password_confirmation, "Confirm temp password" %>
        <%= form.text_field :password_confirmation %>
    </div>

    <template data-fields-target="template">
        <%= form.fields_for :children, Child.new(user_id: @user.id), child_index: 'CHILD' do |f| %>
            <%= render "child_fields", f: f %>
        <% end %>
    </template>

    <%= form.fields_for :children do |f| %>
        <%= render "child_fields", f: f %>
    <% end %>

    <div data-fields-target="target"></div>

    <%= button_tag "Add Child", data: {action: "fields#add"} %>

    <%= form.submit %>
<% end %>

app/views/users/_user.html.erb
<div class="user">
    <h2><%= link_to user.name, user_path(user) %></h2>
    <p>Role: <%= user.role %></p>
    <h3>Contact Information</h3>
    <p>Phone Number: <%= user.phone %></p>
    <p>Email: <%= user.email %></p>
    <%= link_to "Edit user", edit_user_path(user) if current_user.role == "admin" || current_user.role == "school_manager" %>
    <%= link_to "Delete User", user_path(user), data: {turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this #{user.role}?"} if current_user.role == "admin" || current_user.role == "school_manager" %>
</div>

app/views/users/edit.html.erb
<%= render "form", user: @user %>

app/views/users/index.html.erb
<% if current_user.role == "admin" %>
    <%= link_to "New User", new_user_path %>
<% end %>
<%= render @users %>

app/views/users/new.html.erb
<% if current_user.role == "admin" || current_user.role == "school_manager" %>
    <%= render "form" %>
<% else %>
    <%= render "errors/permission" %>
<% end %>

app/views/users/show.html.erb
<%= render @user %>

app/views/users/show_admin.html.erb
<div id="user_show">
    <%= render @user %>

    <% if @user == current_user %>
        <h2>You are an admin</h2>
        <p>With great power, comes great responsibility</p>
    <% end %>
    
    <%= link_to "Add a student", new_child_path(user: @user.id) %>
    
    <% unless @user.children.empty? %>
        <% @user.children.first.events.distinct.each do |event| %>
                <% event_days = event.event_days.map{|ed| ed.id} %>
                <h2><%= link_to event.title, event_path(event) %></h2>
                <div class="event_details child_show">
                    <div class="event_day_container child_show">
                        <div class="name">Name:</div>
                        <%= render event.event_days %>
                        <div class="button_spacer"></div>
                    </div>
                <%= render @user.children, event_days: event_days %>
                </div>
        <% end %>
    <% end %>
</div>

app/views/users/show_caregiver.html.erb
<main id="user_show">
    <%= render @user %>

    
    <% if @user == current_user %>
        <%= link_to "Add a student", new_child_path(user: @user.id) %>

        <% @user.children.first.events.distinct.each do |event| %>
            <% event_days = event.event_days.map{|ed| ed.id} %>
            <h2><%= link_to event.title, event_path(event) %></h2>
            <div class="event_details child_show">
                <div class="event_day_container child_show">
                    <div class="name">Name:</div>
                    <%= render event.event_days %>
                    <div class="button_spacer"></div>
                </div>
            <%= render @user.children, event_days: event_days %>
            </div>
        <% end %>
    <% end %>
</main>

app/views/users/show_school_manager.html.erb
<div id="user_show">
    <%= render @user %>

    <% if @user == current_user %>
        <h2>School manager for:</h2>
        <%= render @user.school %>
    <% end %>
    
    <% unless @user.children.empty? %>
        <%= link_to "Add a student", new_child_path(user: @user.id) %>
        
        <% @user.children.first.events.distinct.each do |event| %>
                <% event_days = event.event_days.map{|ed| ed.id} %>
                <h2><%= link_to event.title, event_path(event) %></h2>
                <div class="event_details child_show">
                    <div class="event_day_container child_show">
                        <div class="name">Name:</div>
                        <%= render event.event_days %>
                        <div class="button_spacer"></div>
                    </div>
                <%= render @user.children, event_days: event_days %>
                </div>
        <% end %>
    <% end %>
</div>