config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: 'd'

  authenticate :user do
    resources :events
    resources :children
    resources :event_days
    resources :schools
    resources :users
    namespace :event_days do
      resources :registrations
    end
  end

  get "/event_splashes/current_event", to: "event_splashes#current_event" 

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  authenticated :user do
    root to: "events#index", as: :authenticated_root
  end
  root to: redirect("/d/sign_in")
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :school

  has_many :event_days, dependent: :destroy
  accepts_nested_attributes_for :event_days
  has_many :children, through: :event_days
  has_many :registrations, through: :event_days

  def children
    super.distinct
  end

  # this is an abomination
  def children_attending
    self.children.reduce(0) do |memo, child|
      if child.registrations.where(attend_morning: true).or(child.registrations.where(attend_afternoon: true)).where(event_day_id: self.event_days.map{|ed| ed.id}).empty?
        memo
      else
        memo += 1
      end 
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all.order(:start_date)
  end
  
  def show
    @event = Event.find(params[:id])
  end
  
  def new
    start_date = Date.parse(params[:start_date])
    end_date = Date.parse(params[:end_date])
    fee = params[:fee]

    num_days = (end_date - start_date).to_i + 1

    if current_user.role != "admin"
      render "errors/permission"
    else
      @event = Event.new(start_date: start_date, end_date: end_date)
      num_days.times do |i|
        @event.event_days << EventDay.new(date: start_date + i.days, fee: fee)
      end
    end
  end
  
  def create
    @event = Event.new(event_params)

    if @event.save
      flash[:notice] = "You've created #{@event.title} for #{@event.school.name}"

      kids = @event.school.children
      event_days = @event.event_days

      event_days.each do |event_day|
        kids.each do |kid|
          event_day.registrations.create(child_id: kid.id, attend_morning: false, attend_afternoon: false)
        end
      end

      redirect_to event_path(@event)
    else
      flash.now[:alert] = "Could not create event"
      render :new, status: :unprocessable_entity
    end
  end
  
  def edit
    @event = Event.find(params[:id])
  end
  
  def update
    @event = Event.find(params[:id])

    if @event.update(event_params)
      flash[:notice] = "#{@event.title} updated successfully"
      redirect_to event_path(@event)
    else
      flash.now[:alert] = "Could not update event"
      render :edit, status: :unprocessable_entity
    end
  end
  
  def destroy
    @event = Event.find(params[:id])
    
    if @event.destroy
      flash[:notice] = "Successfully removed event"
      redirect_to root_path
    else
      flash.now[:alert] = "Could not delete event"
    end
  end

  private

  def event_params
    params.require(:event).permit(:id, :school_id, :title, :description, :start_date, :end_date, event_days_attributes: [:id, :date, :fee, :morning_description, :afternoon_description])
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event.html.erb
<div class="event">
    <h2><%= link_to event.title, event_path(event) %></h2>
    <h3>At <%= event.school.name %></h3>
    <p><%= event.description %></p>
    
    <p>Start Date: <%= event.start_date %></p>
    <p>End Date: <%= event.end_date %></p>
    <p><%= event.children_attending %> children attending</p>

    <% if current_user.role == "admin" %>
        <div class="event_management">
            <%= link_to "Edit Event", edit_event_path(event) %>
            <%= link_to "Delete Event", event_path(event), data: {turbo_method: :delete, turbo_confirm: "Are you sure you want to delete #{event.title} at #{event.school.name}?"} %>
        </div>
    <% end %>
</div>

app/views/events/_event_day_fields.html.erb
<div class="event_day_field">
    <%= f.label :date %>
    <%= f.date_field :date %>    
</div>

<div class="event_day_field">
    <%= f.label :fee %>
    <%= f.number_field :fee %>    
</div>

<div class="event_day_field">
    <%= f.label :morning_description %>
    <%= f.text_area :morning_description %>    
</div>

<div class="event_day_field">
    <%= f.label :afternoon_description %>
    <%= f.text_area :afternoon_description %>    
</div>

app/views/events/_form.html.erb
<%= form_with model: @event do |form| %>

    <h2>Event Details</h2>

    <div class="event_field">
        <%= form.label :school_id %>
        <%= form.collection_select :school_id, School.all, :id, :name %>
    </div>

    <div class="event_field">
        <%= form.label :title %>
        <%= form.text_field :title %>
    </div>  

    <div class="event_field">
        <%= form.label :description %>
        <%= form.text_area :description %>
    </div>  

    <div class="event_field">
        <%= form.label :start_date %>
        <%= form.date_field :start_date %>
    </div>  

    <div class="event_field">
        <%= form.label :end_date %>
        <%= form.date_field :end_date %>
    </div>

    <h2>Event Days</h2>
    
    <%= form.fields_for :event_days do |event_day_form| %>
        <%= render "event_day_fields", f: event_day_form %>
    <% end %>

    <%= form.submit %> 
<% end %>

app/views/events/edit.html.erb
<%= render "form" %>

app/views/events/index.html.erb
<main id="events_index">
    <% if current_user.role == "caregiver" || current_user.role == "school_manager" %>
        <%= render current_user.school.events %>
    <% else %>
        <%= form_with url: new_event_path, method: :get, id: "event_index_form" do |form| %>
            <div class="event_field">
                <%= form.label :start_date %>
                <%= form.date_field :start_date %>
            </div>  

            <div class="event_field">
                <%= form.label :end_date %>
                <%= form.date_field :end_date %>
            </div>

            <div class="event_day_field">
                <%= form.label :fee, "Daily Fee" %>
                <%= form.number_field :fee %>    
            </div>

            <%= form.submit "Create New Event", id: "new_event_submit" %>
        <% end %>

        <div class="event_list">
            <%= render @events %>
        </div>
    <% end %>
</main>

app/views/events/show.html.erb
<main id="event_show">
    <%= render @event %>
    
    <div class="event_days_container">
        <div class="name">Name:</div>
        <%= render @event.event_days %>
        <div class="registration_spacer"></div>
    </div>
    
    <div class="children_container">
        <% if current_user.role == "caregiver" %>
            <%= render current_user.children, event_days: @event.event_days.map{|ed| ed.id} %>
        <% elsif current_user.role == "admin" %>
            <%= render @event.school.children, event_days: @event.event_days.map{|ed| ed.id} %>
        <% elsif current_user.role == "school_manager" %>
            <%= render current_user.school.children, event_days: @event.event_days.map{|ed| ed.id} %>
        <% else %>
            <p>You shouldn't be here....</p>
        <% end %>
    </div>
</main>