config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: 'd'

  authenticate :user do
    resources :events
    resources :children
    resources :event_days
    resources :schools
    resources :users
    namespace :event_days do
      resources :registrations
    end
  end

  get "/event_splashes/current_event", to: "event_splashes#current_event" 

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  authenticated :user do
    root to: "events#index", as: :authenticated_root
  end
  root to: redirect("/d/sign_in")
end

app/models/school.rb
class School < ApplicationRecord
  has_many :events, dependent: :destroy
  has_many :event_days, through: :events
  has_many :users, dependent: :destroy
  accepts_nested_attributes_for :users
  has_many :children, through: :users
  has_many :event_children, through: :events, source: :children
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  def index
    @schools = School.all
  end
  
  def show
    @school = School.find(params[:id])
  end
  
  def new
    @school = School.new
    @school.users.new(role: "school_manager")
  end
  
  def create
    @school = School.new(school_params)

    if @school.save
      flash[:notice] = "You created #{@school.name} school"
      redirect_to school_path(@school)
    else
      flash.now[:alert] = "Could not create school"
      render :new, status: :unprocessable_entity
    end
  end
  
  def edit
    @school = School.find(params[:id])
  end
  
  def update
    @school = School.find(params[:id])

    if @school.update(school_params)
      flash[:notice] = "#{@school.name} updated successfully"
      redirect_to school_path(@school)
    else
      flash.now[:alert] = "Could not update school"
      render :edit, status: :unprocessable_entity
    end
  end
  
  def destroy
    @school = School.find(params[:id])
    
    if @school.destroy
      flash[:notice] = "Successfully removed school"
      redirect_to root_path
    else
      flash.now[:alert] = "Could not delete school"
    end
  end

  private

  def school_params
    params.require(:school).permit(:id, :name, :address, :phone, users_attributes: [:id, :role, :name, :phone, :email, :password, :password_confirmation, :school_id])
  end
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/views/schools/_form.html.erb
<%= form_with model: school do |form| %>
    
    <h2>Register school details</h2>

    <div class="form_field">
        <%= form.label :name %>
        <%= form.text_field :name %>
    </div>

    <div class="form_field">
        <%= form.label :address %>
        <%= form.text_field :address %>
    </div>

    <div class="form_field">
        <%= form.label :phone %>
        <%= form.text_field :phone %>
    </div>

    <h2>Register School Manager</h2>

    <% school.users.each do |user| %>
        <% if user.role == "school_manager" %>
            <%= form.fields_for :users, user do |sm_form| %>

                <%= sm_form.hidden_field :school_id, value: school.id %>
                <%= sm_form.hidden_field :id %>

                <div class="form_field">
                    <%= sm_form.label :role %>
                    <%= sm_form.text_field :role, value: "school_manager", readonly: true %>
                </div>

                <div class="form_field">
                    <%= sm_form.label :name %>
                    <%= sm_form.text_field :name %>
                </div>

                <div class="form_field">
                    <%= sm_form.label :phone %>
                    <%= sm_form.text_field :phone %>
                </div>

                <div class="form_field">
                    <%= sm_form.label :email %>
                    <%= sm_form.text_field :email %>
                </div>

                <div class="form_field">
                    <%= sm_form.label :password, "Temp Password" %>
                    <%= sm_form.text_field :password %>
                </div>

                <div class="form_field">
                    <%= sm_form.label :password_confirmation, "Confirm Temp Password" %>
                    <%= sm_form.text_field :password_confirmation %>
                </div>
            <% end %>
        <% end %>
    <% end %>

    <%= form.submit %>
<% end %>

app/views/schools/_school.html.erb
<div class="school">
    <%= link_to school.name, school_path(school) %>
    <%= school.address %>
    <%= school.phone %>

    <%= link_to "Edit School", edit_school_path(school) %>
</div>
<br>

app/views/schools/edit.html.erb
<%= render "form", school: @school %>

app/views/schools/index.html.erb
<% if current_user.role == "admin" %>
    <%= link_to "Add a school", new_school_path %>
<% end %>

<%= render @schools %>

app/views/schools/new.html.erb
<%= render "form", school: @school %>

app/views/schools/show.html.erb
<main id="school_show">
    <h1><%= @school.name %></h1>
    <h3><%= @school.address %></h3>
    <h3><%= @school.phone %></h3>
    <p>There are <%= @school.children.count %> children enrolled at this school</p>

    <h2>School Events</h2>

    <% @school.events.distinct.each do |event| %>
            <% event_days = event.event_days.map{|ed| ed.id} %>
            <h2><%= link_to event.title, event_path(event) %></h2>
            <div class="event_details child_show">
                <div class="event_day_container child_show">
                    <div class="name">Name:</div>
                    <%= render event.event_days %>
                    <div class="button_spacer"></div>
                </div>
            <%= render @school.children, event_days: event_days %>
            </div>
    <% end %>

    <%= link_to "Delete School", school_path(@school), data: {turbo_method: :delete, turbo_confirm: "Do you really want to delete this school?"} %>
</main>