config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: 'd'

  authenticate :user do
    resources :events
    resources :children
    resources :event_days
    resources :schools
    resources :users
    namespace :event_days do
      resources :registrations
    end
  end

  get "/event_splashes/current_event", to: "event_splashes#current_event" 

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  authenticated :user do
    root to: "events#index", as: :authenticated_root
  end
  root to: redirect("/d/sign_in")
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EventDbPrototype</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% flash.each do |type, msg| %>
      <div class=<%= type %>>
        <%= msg %>
      </div>
    <% end %>

    <% if user_signed_in? %>
      <div id="nav_bar">
        <%= link_to "Home", root_path%>
        <% if current_user.role == "admin" || current_user.role == "school_manager" %>
          <%= link_to "Child List", children_path %>
          <%= link_to "User List", users_path %>
          <%= link_to "School List", schools_path %>
        <% end %>
        <%= link_to "Sign Out", destroy_user_session_path, data: {turbo_method: :delete} %>
        <%= link_to "My Profile", user_path(current_user) %>
      </div>
    <% end %>

    <%= yield %>
  </body>
</html>